active: rmw_zenoh_cpp
middleware:
  rmw_fastrtps_cpp:
    description: FastDDS Middleware
    options:
      FASTDDS_DEFAULT_PROFILES_FILE:
        description: XML profile for FastDDS Configuration
        value: ''
  rmw_zenoh_cpp:
    description: Zenoh Middleware
    options:
      0_ZENOH_ENDPOINTS:
        description: Comma Seperated List of Quoted Endpoints '"tcp/127.0.0.1:7447"'
        value: ''
      0_ZENOH_SHM:
        description: Should Shared Memory be Used
        value: 'false'
      ZENOH_CONFIG_OVERRIDE:
        description: Override Zenoh Config using Environment
        value: connect/endpoints=[${0_ZENOH_ENDPOINTS}];transport/shared_memory/enabled=${0_ZENOH_SHM}
