active: rmw_zenoh_cpp
middleware:
  rmw_fastrtps_cpp:
    description: FastDDS Middleware
    options:
      FASTDDS_DEFAULT_PROFILES_FILE:
        description: XML profile for FastDDS Configuration
        value: ''
  rmw_zenoh_cpp:
    description: Zenoh Middleware
    env:
      ZENOH_CONFIG_OVERRIDE: connect/endpoints=[${ZENOH_ENDPOINTS}];transport/shared_memory/enabled=${ZENOH_SHM}
    options:
      ZENOH_ENDPOINTS:
        description: Comma Seperated List of Quoted Endpoints '"tcp/127.0.0.1:7447"'
        value: ''
      ZENOH_SHM:
        description: Should Shared Memory be Used
        value: 'false'
